
package notemakemenu;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import callenderframing.SchedulerCalPage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javaclasses.SettingWallPaper;
import javax.swing.DefaultListModel;

/**
 *
 * @author aks
 */
public class ViewAll extends javax.swing.JFrame {
    int xx;
    int xy;
    SettingWallPaper s;
    private static ViewAll obj=null;
     public String savePath=System.getProperty("user.home")+"/Documents/DigitalDiary/";
     public String savePat=System.getProperty("user.home")+"/Documents/specialEventsLog.MyApps/";
    /**
     * Creates new form ViewAll
     */
    public ViewAll() {
        initComponents();
        
    }
    
    public static  ViewAll getObj(){
    if(obj==null){
        obj=new ViewAll();
    }
    return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listNotes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSpecialEvents = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Show All");
        setMaximumSize(new java.awt.Dimension(544, 450));
        setMinimumSize(new java.awt.Dimension(544, 450));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        listNotes.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(listNotes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 171, 248, 268);

        listSpecialEvents.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(listSpecialEvents);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(276, 171, 258, 268);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All Notes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 151, 132, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("All Special Events");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(287, 151, 124, 14);

        dateLbl.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(255, 51, 102));
        dateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dateLbl);
        dateLbl.setBounds(130, 43, 266, 62);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 0, 40, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("x");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 0, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picturesdownloaded/NewLayer.jpg"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 550, 450);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultListModel dn=(DefaultListModel)listNotes.getModel();
        DefaultListModel ds=(DefaultListModel)listSpecialEvents.getModel();
        
        dateLbl.setText(SchedulerCalPage.selectedDate+" - "+SchedulerCalPage.selectedMonth+" - "+SchedulerCalPage.selectedYear);
        
        try
        {
            if((new File(savePath+"allNotesLog.dat")).exists())
            {
                BufferedReader br = new BufferedReader(new FileReader(savePath+"allNotesLog.dat"));
                String s="";
                String date, month, year;
                while((s=br.readLine())!=null)
                {
                    date=s.substring(s.lastIndexOf("@")+1, s.lastIndexOf("-")).trim();
                    System.out.println(""+date);
                    month=s.substring(s.lastIndexOf("-")+1, s.lastIndexOf("_")).trim();
                    System.out.println("    "+month);
                    year=s.substring(s.lastIndexOf("_")+1,s.lastIndexOf(".")).trim();
                    System.out.println(""+year);
                    int d=Integer.parseInt(date);
                    int m=Integer.parseInt(month);
                    int y=Integer.parseInt(year);
                    if(d==SchedulerCalPage.selectedDate && m==SchedulerCalPage.selectedMonth && y==SchedulerCalPage.selectedYear)
                        dn.addElement(s);
                }
                br.close();
            }
            if((new File(savePat+"specialEventsLog.dat")).exists())
            {
                BufferedReader b = new BufferedReader(new FileReader(savePat+"specialEventsLog.dat"));
                String str="";
                while((str=b.readLine())!=null)
                {
                    String date=str.substring(str.lastIndexOf("#")+1, str.lastIndexOf("*")).trim();
                    String month=str.substring(str.lastIndexOf("*")+1, str.lastIndexOf("~")).trim();
                    String year=str.substring(str.lastIndexOf("~")+1).trim();
                    int d=Integer.parseInt(date);
                    int m=Integer.parseInt(month);
                    int y=Integer.parseInt(year);
                    if(d==SchedulerCalPage.selectedDate && m==SchedulerCalPage.selectedMonth && y==SchedulerCalPage.selectedYear)
                    ds.addElement(str.substring(0,str.lastIndexOf("#")));
                }
                b.close();
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
       int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jLabel3MouseDragged

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
      this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        dispose();
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
       xx=evt.getX();
       xy=evt.getY();
    }//GEN-LAST:event_jLabel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listNotes;
    private javax.swing.JList<String> listSpecialEvents;
    // End of variables declaration//GEN-END:variables
}
