/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sendsms;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.mail.internet.MimeMessage.*;
import javax.swing.JOptionPane;

/**
 *
 * @author babaoye ayomide
 */
public class NewJFrame extends javax.swing.JFrame {
    private static NewJFrame obj=null;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
    }
    public static NewJFrame getObj(){
        if(obj==null){
            obj= new NewJFrame();
        }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(318, 310));
        setMinimumSize(new java.awt.Dimension(318, 310));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(318, 310));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Number");
        jLabel1.setMaximumSize(new java.awt.Dimension(324, 310));
        jLabel1.setMinimumSize(new java.awt.Dimension(324, 310));
        jLabel1.setPreferredSize(new java.awt.Dimension(324, 310));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 54, 50, 20);

        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 50, 14);

        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("TextArea");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(15, 180, 70, 14);

        jTextField1.setText("@txtlocal.co.uk");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(90, 50, 166, 28);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 170, 210, 110);

        jButton1.setText("Send Sms");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 290, 100, 23);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(90, 130, 166, 32);

        jLabel4.setForeground(new java.awt.Color(255, 0, 102));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 60, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(90, 90, 166, 34);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("x");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 0, 40, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("-");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 0, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picturesdownloaded/NewLayer.jpg"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(318, 310));
        jLabel5.setMinimumSize(new java.awt.Dimension(318, 310));
        jLabel5.setPreferredSize(new java.awt.Dimension(318, 310));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 320, 310);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String host="smtp.gmail.com";
            String user=jTextField1.getText();
            String pass=jPasswordField2.getText();
            String to=jTextField2.getText();
            String from=user;
            String subject="Message";
            String message=jTextArea1.getText();
            boolean sessionDebug=false;
            Properties prop=System.getProperties();
            prop.put("mail.smtp.starttls.enable","true");
            prop.put("mail.smtp.host","host");
            prop.put("mail.smtp.auth","true");
            prop.put("mail.smtp.port","587");
            prop.put("mail.smtp.starttls.required","true");
            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            Session MailSession =Session.getDefaultInstance(prop,null);
            MailSession.setDebug(sessionDebug);
            Message mesg=new MimeMessage(MailSession);
            mesg.setFrom(new InternetAddress(from));
            InternetAddress [] address = {new InternetAddress(to)};
            mesg.setRecipients(Message.RecipientType.TO, address);
            mesg.setSubject(subject);
            mesg.setSentDate(new Date());
            mesg.setText(message);
            Transport trans=MailSession.getTransport();
            trans.connect(host,user,pass);
            trans.sendMessage(mesg, mesg.getAllRecipients());
            trans.close();
            JOptionPane.showMessageDialog(null,"All messages are sent");
            
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
