/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package speechschedulerprogram;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaclasses.SettingWallPaper;
import javaclasses.WallValidity;
import javax.swing.ImageIcon;

/**
 *
 * @author babaoye ayomide
 */
public class ChangeWallpaper extends javax.swing.JFrame {
SettingWallPaper s;
private static ChangeWallpaper obj=null;
    /**
     * Creates new form ChangeWallpaper
     */
    public ChangeWallpaper() {
        initComponents();
        WallValidity wv=new WallValidity();
        wv.SetWallPaper();
        s=new SettingWallPaper();
    }
     public static ChangeWallpaper getObj(){
        if(obj==null){
            obj=new ChangeWallpaper();
                   }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picturesdownloaded/backgroundass4.jpg"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picturesdownloaded/backgroundass5.jpg"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picturesdownloaded/backgroundass6.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picturesdownloaded/backgroundass1.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel120.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel120.setForeground(new java.awt.Color(255, 255, 255));
        jLabel120.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel120.setText("-");
        jLabel120.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel120MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 40, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("x");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 30, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picturesdownloaded/backgroundass2.jpg"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picturesdownloaded/backgroundass3.jpg"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picturesdownloaded/NewLayer.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel120MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel120MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel120MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        setVisible(false); 
        SettingWallPaper s=new SettingWallPaper();
        if(s.Readwallpaper().equals("wall1")){
            try {
                File f=new File("picturesdownloaded/background3.jpg");
                System.out.println(f.getCanonicalPath()+" "+f.exists());
                URL url;
                url = getClass().getResource("/background3.jpg");
                ImageIcon i=new ImageIcon(url);
                LoginPage.jLabel1.setIcon(i);
            } catch (IOException ex) {
                Logger.getLogger(WallValidity.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(s.Readwallpaper().equals("wall2")){
            try {
                File f=new File("picturesdownloaded/background4.jpg");
                System.out.println(f.getCanonicalPath()+" "+f.exists());
                URL url=getClass().getResource("/background4.jpg");
                ImageIcon i=new ImageIcon(url);
                LoginPage.jLabel1.setIcon(i);
                
            } catch (IOException ex) {
                Logger.getLogger(WallValidity.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         else if(s.Readwallpaper().equals("wall3")){
            try {
                File f=new File("picturesdownloaded/background.jpeg");
                System.out.println(f.getCanonicalPath()+""+f.exists());
                URL url=getClass().getResource("/background.jpeg");
                ImageIcon i=new ImageIcon(url);
                LoginPage.jLabel1.setIcon(i);
            } catch (IOException ex) {
                Logger.getLogger(WallValidity.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         else if(s.Readwallpaper().equals("wall4")){
            try {
                File f=new File("picturesdownloaded/background2.jpeg");
                System.out.println(f.getCanonicalPath()+""+f.exists());
                ImageIcon i=new ImageIcon(getClass().getResource("/picturesdownloaded/background2.jpeg"));
                LoginPage.jLabel1.setIcon(i);
            } catch (IOException ex) {
                Logger.getLogger(WallValidity.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         else if(s.Readwallpaper().equals("wall5")){
            try {
                File f=new File("picturesdownloaded/background5.jpg");
                System.out.println(f.getCanonicalPath()+""+f.exists());
                URL url=Class.class.getResource("/background5.jpg");
                ImageIcon i=new ImageIcon(url);
                LoginPage.jLabel1.setIcon(i);
            } catch (IOException ex) {
                Logger.getLogger(WallValidity.class.getName()).log(Level.SEVERE, null, ex);
            }
      
        }
         else if(s.Readwallpaper().equals("wall6")){
            try {
                File f=new File("picturesdownloaded/NewLayer.jpg");
                System.out.println(f.getCanonicalPath()+""+f.exists());
                URL url=Class.class.getResource("/NewLayer.jpg");
                ImageIcon i=new ImageIcon(url);
                LoginPage.jLabel1.setIcon(i);
            } catch (IOException ex) {
                Logger.getLogger(WallValidity.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
                File f=new File("picturesdownloaded/background3.jpg");
                System.out.println(f.getCanonicalPath()+" "+f.exists());
                URL url;
                url = getClass().getResource("/background3.jpg");
                ImageIcon i=new ImageIcon(url);
                jLabel1.setIcon(i);
                s.WriteWallPaper("wall1");
            } catch (IOException ex) {
                Logger.getLogger(WallValidity.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       try {
                File f=new File("picturesdownloaded/background4.jpg");
                System.out.println(f.getCanonicalPath()+" "+f.exists());
                URL url=getClass().getResource("/background4.jpg");
                ImageIcon i=new ImageIcon(url);
                jLabel1.setIcon(i);
                s.WriteWallPaper("wall2");
            } catch (IOException ex) {
                Logger.getLogger(WallValidity.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try {
                File f=new File("picturesdownloaded/background.jpeg");
                System.out.println(f.getCanonicalPath()+""+f.exists());
                URL url=getClass().getResource("/background.jpeg");
                ImageIcon i=new ImageIcon(url);
                jLabel1.setIcon(i);
                s.WriteWallPaper("wall3");
            } catch (IOException ex) {
                Logger.getLogger(WallValidity.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
      try {
                File f=new File("picturesdownloaded/background2.jpeg");
                System.out.println(f.getCanonicalPath()+""+f.exists());
                ImageIcon i=new ImageIcon(getClass().getResource("/picturesdownloaded/background2.jpeg"));
                jLabel1.setIcon(i);
                s.WriteWallPaper("wall4");
            } catch (IOException ex) {
                Logger.getLogger(WallValidity.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
      try {
                File f=new File("picturesdownloaded/background5.jpg");
                System.out.println(f.getCanonicalPath()+""+f.exists());
                URL url=Class.class.getResource("/background5.jpg");
                ImageIcon i=new ImageIcon(url);
                jLabel1.setIcon(i);
                s.WriteWallPaper("wall5");
            } catch (IOException ex) {
                Logger.getLogger(WallValidity.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       try {
                File f=new File("picturesdownloaded/NewLayer.jpg");
                System.out.println(f.getCanonicalPath()+""+f.exists());
                URL url=Class.class.getResource("/NewLayer.jpg");
                ImageIcon i=new ImageIcon(url);
                jLabel1.setIcon(i);
                s.WriteWallPaper("wall6");
            } catch (IOException ex) {
                Logger.getLogger(WallValidity.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeWallpaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeWallpaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeWallpaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeWallpaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeWallpaper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
